### ISSUE TITLE
示例代码报错“TypeError: unsupported operand type(s) for -: 'int' and 'list'”

### ISSUE THREAD

**Issue by MACRO-e** [UePG-21/gpquant#1]
你好！我在运行gpquant实例代码的时候出现了报错，报错如下：
“TypeError: unsupported operand type(s) for -: 'int' and 'list'”

![image](https://user-images.githubusercontent.com/67302876/176994273-df8fc752-fbf7-46bd-8f0e-b33ef7442b14.png)
请问这是什么原因造成的呢？谢谢！

**Comment by UePG-21** [comment]
收到了您的信息，我现在人在外面，等我这几天有空检查一下～谢谢您的反馈！

**Comment by UePG-21** [comment]
sorry给您造成了困扰😅

**Comment by UePG-21** [comment]
如果您等不急的话也可以在我github里看下源码检查，不急的话我下周会有时间来看～
