### ISSUE TITLE
多个序列fit

### ISSUE THREAD

**Issue by chesterai** [UePG-21/gpquant#2]
请问如何fit多个股票序列呢，这个项目看起来只能fit一支股票，不知道有没有pandas groupby等trick能找到多个股票上同时fitness比较好的因子

**Comment by UePG-21** [comment]
当时开发确实是用来做单品种期货因子的，如果多个股票的话我觉得需要改一下回测方式吧，因为fit多个股票相当于要选股了，回测逻辑复杂一些。可以试一试修改Backtester部分，但我没尝试过，没法给出具体方案。

**Comment by chesterai** [comment]
我运行股票数据后，出现了无法避免的nan错误，不知是否可以提供一下你这边的sample data呢？

**Comment by UePG-21** [comment]
我用的数据已经清理了，当时是可以跑通的，你试着debug一下？或者你可以把数据发我，我有空帮你看看什么问题。

**Comment by chesterai** [comment]
请问该如何发数据给您呢？

**Comment by UePG-21** [comment]
hanlin.warng@gmail.com
您自己也先试试debug哈，我最近有点忙，可能过几天给您看下。
