### ISSUE TITLE
Seems gpquant not support multi-process .

### ISSUE THREAD

**Issue by baikai** [UePG-21/gpquant#4]
Seems gpquant not support multi-process ,  cannot find parameters like 'n_jobs' in gplearn to control concurrency . 
SymbolicRegressor logic running inside one process, and will be very slow if we use large dataset.

**Comment by UePG-21** [comment]
Oh, that's right. Maybe try paralleling the fitness calculation part for each tree :)

**Comment by baikai** [comment]
Thanks, I will try to accelerate it by use GPU, and also should modify some functions code.

**Comment by UePG-21** [comment]
Sure!
