### ISSUE TITLE
How to use backtester?

### ISSUE THREAD

**Issue by Kiattisak-Rattanaporn** [UePG-21/gpquant#6]
Do I understand correctly that if I want to use metrics such as annual return or shape ratio, I need to set the parameter 'transformer' to 'quantile'? I am then wondering about the method of specifying 'transformer_kwargs' in order to use that metric. And how do we set up the DataFrame (df) and signal for the backtester?"

Thank!

**Comment by UePG-21** [comment]
Transformer is used to convert your factor to a strategy signal. You can define your own version but here I take a quantile strategy as an example.

df should contain OHLCVAB in columns and index is the time.

See test.py for details.

**Comment by acy925** [comment]
> Transformer is used to convert your factor to a strategy signal. You can define your own version but here I take a quantile strategy as an example.
> 
> df should contain OHLCVAB in columns and index is the time.
> 
> See test.py for details.

So, the data.csv file in test.py is one stock's df data, right?

**Comment by UePG-21** [comment]
Correct.

**Comment by Kiattisak-Rattanaporn** [comment]
If I want to use the best estimator in a custom fitness function, is there a way to pass the best estimator as an input to the custom fitness function?

**Comment by UePG-21** [comment]
Yes, transformer, as a kind of strategy, converts the estimator to another series for the fitness to evaluate. A typical use in the quant trading is that the estimator is a factor, then, with a specified strategy, we can convert this factor to a signal and to a strategy return series. Then we use fitness to calculate the Sharpe ratio of this return series.
