### ISSUE TITLE
no more Generation

### ISSUE THREAD

**Issue by SAMPLE-42** [UePG-21/gpquant#7]
传入数据后似乎没有迭代，并且好像调不到时序函数

<img width="951" alt="微信图片_20231229111728" src="https://github.com/UePG-21/gpquant/assets/109020625/00800c53-932b-493c-90af-7bc1e33c9715">

**Comment by UePG-21** [comment]
深度设置？

**Comment by SAMPLE-42** [comment]
<img width="934" alt="微信图片_20231229114100" src="https://github.com/UePG-21/gpquant/assets/109020625/b63f8c05-d4cf-4516-9249-21e2a0463b65">
整个的参数设置如上述

**Comment by SAMPLE-42** [comment]
<img width="1134" alt="微信图片_20231229115855" src="https://github.com/UePG-21/gpquant/assets/109020625/0d4fd2fa-8bc5-427c-a050-0ec2794879ce">
添加进度条，发现迭代可能没有进行就输出了

**Comment by UePG-21** [comment]
哦哦，那现在ok了是吧？

**Comment by SAMPLE-42** [comment]
感觉有点奇怪，是否是早停的逻辑不太合理？注释以后可以迭代，但是还是很难抽到时序函数
<img width="506" alt="微信图片_20231229120612" src="https://github.com/UePG-21/gpquant/assets/109020625/a454e9ed-9d68-4a35-bbff-0db31d03affa">

**Comment by UePG-21** [comment]
跟early stop应该没关系，你check一下每轮所有的tree长什么样，有没有时序函数，如果有的话只能说明他们最后被优化掉了
