### ISSUE TITLE
the problem of sharpe_ratio

### ISSUE THREAD

**Issue by SAMPLE-42** [UePG-21/gpquant#8]
<img width="535" alt="微信图片_20240109105621" src="https://github.com/UePG-21/gpquant/assets/109020625/ca9a0d6d-67eb-429c-88b7-d427db2a6ef1">
请问代码中调整的夏普指的是什么，这样做的目的是什么，直接将无风险收益率变小，使夏普比率为正来优化目标适合会更合理呢。感谢大佬回复！

**Comment by UePG-21** [comment]
调如果超额收益为负，那根据原来的计算公式vol应该越大越好，但实际我们希望要小的vol，所以不调整会遗传出很多大vol，根据超额收益的正负用合适的fitness有助于快点找到好的tree

**Comment by SAMPLE-42** [comment]
感谢大佬解惑！
