### ISSUE TITLE
进化方式

### ISSUE THREAD

**Issue by SAMPLE-42** [UePG-21/gpquant#9]
你好大佬，请问代码中的轮盘赌的方式是否是每次随机选择，而没有对前一个子代的优质公式进行保留，用于变异进化

**Comment by UePG-21** [comment]
每次进化肯定选的是tournament里fitness最好的呀

**Comment by SAMPLE-42** [comment]
但是似乎tournament抽取的公式池是每次依据种群大小重新随机的

**Comment by UePG-21** [comment]
![image](https://github.com/UePG-21/gpquant/assets/81507788/295cb196-2f09-4a48-be31-093a2f8e1a7c)
抽取是随机的，但比完fitness排序了，没排序可是重大bug

**Comment by SAMPLE-42** [comment]
确实是排序，整理逻辑是随机生成population_size个公式，然后抽取tourament_size个，计算最大的适应度的公式作为父代，然后进行进化变异，但是当generations不等于1时，每次的上述过程似乎是相互独立，如果是相互独立，那么整个运行不就接近存粹的随机算法了吗

**Comment by UePG-21** [comment]
那不是的，比如population有1000个，我每次选20个举行tournament，留下最好的一个或两个（取决于mutation方式），每次tournament都是独立的，但每次都选出来的是tournament里最好的，所以跟绝对的随机还是有区别的。之所以这样做是为了保证每次在选出fitness相对高的tree时还能有一定的随机性，而不是每次都用最最好的一部分。

**Comment by UePG-21** [comment]
举一个极端的例子，这种选法不可能选出最差的19个，但随机选可能选到，所以二者是不等价的

**Comment by SAMPLE-42** [comment]
了解，感谢解惑。另外，代码似乎极易过拟合，而且挖掘出来的样本内模式似乎都特别像

**Comment by UePG-21** [comment]
过拟合在遗传里很正常，后续可以筛选下，我很久没看遗传相关的了，不过这里面有很多trick，可以参考参考别的实现或者论文

**Comment by SAMPLE-42** [comment]
目前的想法是进行多次训练，然后总结公式最短并且适应度高的新算子，进行分层搜索，在获取并总结算子上大佬有什么建议吗

**Comment by UePG-21** [comment]
不是大佬hh，其实我觉得validation就行了，样本外好的基本都能好一段时间

**Comment by SAMPLE-42** [comment]
hhh，在你的框架上每次输出一个公式，如果重新训练很容易得到类似的，我又想尽可能得到不同其样本外好的公式，所以需要对他进行引导搜索

**Comment by UePG-21** [comment]
其实我当时在用的时候没有发现公式很类似的情况，可能现在市场变了

**Comment by SAMPLE-42** [comment]
原来是这样，再次感谢大佬回复hhh
